import type { Metadata } from "next";
import "./globals.css";
import AppHeader from "@/components/AppHeader";
import LoggedInFooter from "@/components/LoggedInFooter";
import SiteFooter from "@/components/SiteFooter";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `(function(){var t=localStorage.getItem("theme");var d=t==="dark"||(t!=="light"&&window.matchMedia("(prefers-color-scheme: dark)").matches);if(d)document.documentElement.classList.add("dark");else document.documentElement.classList.remove("dark");})();`,
          }}
        />
      </head>
      <body className="antialiased">
        <div className="flex min-h-screen flex-col">
          <AppHeader />

          <main className="mx-auto flex w-full max-w-5xl flex-1 px-4 py-8 pb-20">
            {children}
          </main>

          <LoggedInFooter />

          <SiteFooter />
        </div>
      </body>
    </html>
  );
}
